(function(root,factory){'use strict';const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root)root.ZeroBudgetStorageEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const ROOT_KEY='zeroBudget_data',JOURNAL_KEY='zeroBudget_journal',WRITE_LOCK_KEY='zeroBudget_write_lock',MANIFEST_PREFIX='zeroBudget_manifest:',GLOBAL_PREFIX='zeroBudget_global:',MONTH_PREFIX='zeroBudget_month:';
const DEFAULT_LOCK_TTL_MS=5000,SHARDED_LOCK_TTL_MS=8000,DEFAULT_LOCK_RENEWAL_MS=2500,FORMAT_VERSION=1;
const GEN=/^\d{8}T\d{9}Z-[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,MONTH=/^\d{4}-(0[1-9]|1[0-2])$/,BLOCKED=new Set(['__proto__','prototype','constructor']);
function err(code,path='$'){const e=new Error(`Sharded layout error (${code})`);e.name='ShardedLayoutError';e.code=code;e.path=path;return e;}function fail(c,p){throw err(c,p);}
function object(v,p){if(v===null||typeof v!=='object'||Array.isArray(v)||(Object.getPrototypeOf(v)!==Object.prototype&&Object.getPrototypeOf(v)!==null))fail('EXPECTED_OBJECT',p);for(const k of Reflect.ownKeys(v)){if(typeof k!=='string')fail('SYMBOL_KEY',p);if(BLOCKED.has(k))fail('UNSAFE_KEY',`${p}.${k}`);const d=Object.getOwnPropertyDescriptor(v,k);if(!d.enumerable||!Object.hasOwn(d,'value'))fail('NON_DATA_PROPERTY',`${p}.${k}`);}}
function exact(v,keys,p='$'){object(v,p);const s=new Set(keys);for(const k of Object.keys(v))if(!s.has(k))fail('UNKNOWN_FIELD',`${p}.${k}`);for(const k of keys)if(!Object.hasOwn(v,k))fail('MISSING_FIELD',`${p}.${k}`);}
function parse(t){if(typeof t!=='string')fail('EXPECTED_JSON_TEXT','$');try{return JSON.parse(t);}catch{fail('INVALID_JSON','$');}}function copy(v){return JSON.parse(JSON.stringify(v));}
function gen(v,p){if(typeof v!=='string'||!GEN.test(v))fail('INVALID_GENERATION',p);}function schema(v,p){if(![3,4,5].includes(v))fail('UNSUPPORTED_SCHEMA_VERSION',p);}function month(v,p){if(typeof v!=='string'||!MONTH.test(v))fail('INVALID_MONTH',p);}function stamp(v,p){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(v)||!Number.isFinite(Date.parse(v)))fail('INVALID_TIMESTAMP',p);}function time(v,p){if(!Number.isSafeInteger(v)||v<0)fail('INVALID_TIME',p);}
const manifestKey=g=>`${MANIFEST_PREFIX}${g}`,globalKey=g=>`${GLOBAL_PREFIX}${g}`,monthKey=(g,m)=>`${MONTH_PREFIX}${g}:${m}`;
function createGenerationId(date=new Date(),uuid){if(!(date instanceof Date)||!Number.isFinite(date.getTime()))fail('INVALID_TIMESTAMP','$.date');const id=uuid===undefined?(globalThis.crypto&&typeof globalThis.crypto.randomUUID==='function'?globalThis.crypto.randomUUID():null):uuid;if(typeof id!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(id))fail('INVALID_UUID','$.uuid');return `${date.toISOString().replace(/[-:.]/g,'')}-${id}`;}
function common(v,format,keys){exact(v,keys);if(v.format!==format)fail('INVALID_FORMAT','$.format');if(v.formatVersion!==1)fail('INVALID_FORMAT_VERSION','$.formatVersion');}
function utf8Length(value){let length=0;for(const symbol of value){const code=symbol.codePointAt(0);length+=code<=0x7f?1:code<=0x7ff?2:code<=0xffff?3:4;}return length;}
function sha256(text){const right=(v,n)=>(v>>>n)|(v<<(32-n)),max=Math.pow(2,32),words=[],bytes=[];for(const symbol of text){const code=symbol.codePointAt(0);if(code<=0x7f)bytes.push(code);else if(code<=0x7ff)bytes.push(0xc0|(code>>6),0x80|(code&63));else if(code<=0xffff)bytes.push(0xe0|(code>>12),0x80|((code>>6)&63),0x80|(code&63));else bytes.push(0xf0|(code>>18),0x80|((code>>12)&63),0x80|((code>>6)&63),0x80|(code&63));}const bitLength=bytes.length*8;bytes.push(0x80);while(bytes.length%64!==56)bytes.push(0);for(let i=7;i>=0;i--)bytes.push(i<4?(bitLength>>>i*8)&255:0);const primes=[],hash=[];for(let candidate=2;primes.length<64;candidate++){let prime=true;for(let d=2;d*d<=candidate;d++)if(candidate%d===0){prime=false;break;}if(prime){primes.push(candidate);if(hash.length<8)hash.push((Math.sqrt(candidate)*max)|0);}}const k=primes.map(p=>(Math.cbrt(p)*max)|0);for(let offset=0;offset<bytes.length;offset+=64){for(let i=0;i<16;i++)words[i]=(bytes[offset+i*4]<<24)|(bytes[offset+i*4+1]<<16)|(bytes[offset+i*4+2]<<8)|bytes[offset+i*4+3];for(let i=16;i<64;i++){const a=words[i-15],b=words[i-2],s0=right(a,7)^right(a,18)^(a>>>3),s1=right(b,17)^right(b,19)^(b>>>10);words[i]=(words[i-16]+s0+words[i-7]+s1)|0;}let [a,b,c,d,e,f,g,h]=hash;for(let i=0;i<64;i++){const s1=right(e,6)^right(e,11)^right(e,25),ch=(e&f)^(~e&g),t1=(h+s1+ch+k[i]+words[i])|0,s0=right(a,2)^right(a,13)^right(a,22),maj=(a&b)^(a&c)^(b&c),t2=(s0+maj)|0;h=g;g=f;f=e;e=(d+t1)|0;d=c;c=b;b=a;a=(t1+t2)|0;}hash[0]=(hash[0]+a)|0;hash[1]=(hash[1]+b)|0;hash[2]=(hash[2]+c)|0;hash[3]=(hash[3]+d)|0;hash[4]=(hash[4]+e)|0;hash[5]=(hash[5]+f)|0;hash[6]=(hash[6]+g)|0;hash[7]=(hash[7]+h)|0;}return hash.map(v=>(v>>>0).toString(16).padStart(8,'0')).join('');}
function buildRootPointer({generation:g,residentSchemaVersion:s,committedAt:c}){gen(g,'$.generation');schema(s,'$.residentSchemaVersion');stamp(c,'$.committedAt');return Object.freeze({format:'zerobudget-active-layout',formatVersion:1,layout:'month-sharded',generation:g,manifestKey:manifestKey(g),residentSchemaVersion:s,committedAt:c});}
function parseRootPointer(t){const v=parse(t);common(v,'zerobudget-active-layout',['format','formatVersion','layout','generation','manifestKey','residentSchemaVersion','committedAt']);if(v.layout!=='month-sharded')fail('INVALID_LAYOUT','$.layout');gen(v.generation,'$.generation');if(v.manifestKey!==manifestKey(v.generation))fail('INVALID_KEY_REFERENCE','$.manifestKey');schema(v.residentSchemaVersion,'$.residentSchemaVersion');stamp(v.committedAt,'$.committedAt');return copy(v);}
function checkMonths(a,p='$.monthOrder'){if(!Array.isArray(a))fail('EXPECTED_ARRAY',p);a.forEach((m,i)=>month(m,`${p}[${i}]`));if(new Set(a).size!==a.length)fail('DUPLICATE_MONTH',p);if(a.some((m,i)=>i&&a[i-1]>=m))fail('UNSORTED_MONTHS',p);}
function checkDigest(v,p){if(typeof v!=='string'||!/^[0-9a-f]{64}$/.test(v))fail('INVALID_SHA256',p);}function checkSize(v,p){if(!Number.isSafeInteger(v)||v<0)fail('INVALID_BYTE_LENGTH',p);}
function globalReference(raw,envelope=parseGlobalShard(raw)){const ref={key:globalKey(envelope.generation),generation:envelope.generation,residentSchemaVersion:envelope.residentSchemaVersion,byteLength:utf8Length(raw),sha256:sha256(raw)};return Object.freeze(ref);}
function monthReference(raw,envelope=parseMonthShard(raw)){const ref={key:monthKey(envelope.generation,envelope.monthKey),generation:envelope.generation,monthKey:envelope.monthKey,residentSchemaVersion:envelope.residentSchemaVersion,byteLength:utf8Length(raw),sha256:sha256(raw)};return Object.freeze(ref);}
function checkGlobalRef(v,s,p='$.global'){exact(v,['key','generation','residentSchemaVersion','byteLength','sha256'],p);gen(v.generation,`${p}.generation`);schema(v.residentSchemaVersion,`${p}.residentSchemaVersion`);if(v.residentSchemaVersion!==s)fail('MIXED_SCHEMA',`${p}.residentSchemaVersion`);if(v.key!==globalKey(v.generation))fail('INVALID_KEY_REFERENCE',`${p}.key`);checkSize(v.byteLength,`${p}.byteLength`);checkDigest(v.sha256,`${p}.sha256`);}
function checkMonthRef(v,s,m,p){exact(v,['key','generation','monthKey','residentSchemaVersion','byteLength','sha256'],p);gen(v.generation,`${p}.generation`);schema(v.residentSchemaVersion,`${p}.residentSchemaVersion`);month(v.monthKey,`${p}.monthKey`);if(v.monthKey!==m)fail('MIXED_MONTH',`${p}.monthKey`);if(v.residentSchemaVersion!==s)fail('MIXED_SCHEMA',`${p}.residentSchemaVersion`);if(v.key!==monthKey(v.generation,m))fail('INVALID_KEY_REFERENCE',`${p}.key`);checkSize(v.byteLength,`${p}.byteLength`);checkDigest(v.sha256,`${p}.sha256`);}
function validateGlobalReference(ref,raw){checkGlobalRef(ref,ref.residentSchemaVersion);if(utf8Length(raw)!==ref.byteLength)fail('BYTE_LENGTH_MISMATCH','$.global.byteLength');if(sha256(raw)!==ref.sha256)fail('SHA256_MISMATCH','$.global.sha256');const envelope=parseGlobalShard(raw,ref.generation,ref.residentSchemaVersion);if(ref.key!==globalKey(envelope.generation))fail('INVALID_KEY_REFERENCE','$.global.key');return envelope;}
function validateMonthReference(ref,raw){checkMonthRef(ref,ref.residentSchemaVersion,ref.monthKey,'$.month');if(utf8Length(raw)!==ref.byteLength)fail('BYTE_LENGTH_MISMATCH','$.month.byteLength');if(sha256(raw)!==ref.sha256)fail('SHA256_MISMATCH','$.month.sha256');const envelope=parseMonthShard(raw,ref.generation,ref.residentSchemaVersion,ref.monthKey);if(ref.key!==monthKey(envelope.generation,envelope.monthKey))fail('INVALID_KEY_REFERENCE','$.month.key');return envelope;}
function buildManifest({generation:g,residentSchemaVersion:s,committedAt:c,global,monthOrder:o,months}){gen(g,'$.generation');schema(s,'$.residentSchemaVersion');stamp(c,'$.committedAt');checkMonths(o);checkGlobalRef(global,s);object(months,'$.months');const keys=Object.keys(months).sort();if(keys.length!==o.length||keys.some((m,i)=>m!==o[i]))fail('MONTH_REFERENCE_MISMATCH','$.months');o.forEach(m=>checkMonthRef(months[m],s,m,`$.months.${m}`));return Object.freeze({format:'zerobudget-active-manifest',formatVersion:1,layout:'month-sharded',generation:g,residentSchemaVersion:s,committedAt:c,global:Object.freeze(copy(global)),monthOrder:Object.freeze([...o]),months:Object.freeze(copy(months))});}
function parseManifest(t,expected){const v=parse(t);common(v,'zerobudget-active-manifest',['format','formatVersion','layout','generation','residentSchemaVersion','committedAt','global','monthOrder','months']);if(v.layout!=='month-sharded')fail('INVALID_LAYOUT','$.layout');gen(v.generation,'$.generation');if(expected!==undefined&&v.generation!==expected)fail('MIXED_GENERATION','$.generation');schema(v.residentSchemaVersion,'$.residentSchemaVersion');stamp(v.committedAt,'$.committedAt');checkGlobalRef(v.global,v.residentSchemaVersion);checkMonths(v.monthOrder);object(v.months,'$.months');const ks=Object.keys(v.months).sort();if(ks.length!==v.monthOrder.length||ks.some((m,i)=>m!==v.monthOrder[i]))fail('MONTH_REFERENCE_MISMATCH','$.months');v.monthOrder.forEach(m=>checkMonthRef(v.months[m],v.residentSchemaVersion,m,`$.months.${m}`));return copy(v);}
function buildGlobalShard({generation:g,residentSchemaVersion:s,data:d}){gen(g,'$.generation');schema(s,'$.residentSchemaVersion');object(d,'$.data');return Object.freeze({format:'zerobudget-active-global',formatVersion:1,layout:'month-sharded',generation:g,residentSchemaVersion:s,data:copy(d)});}
function parseGlobalShard(t,g,s){const v=parse(t);common(v,'zerobudget-active-global',['format','formatVersion','layout','generation','residentSchemaVersion','data']);if(v.layout!=='month-sharded')fail('INVALID_LAYOUT','$.layout');gen(v.generation,'$.generation');schema(v.residentSchemaVersion,'$.residentSchemaVersion');object(v.data,'$.data');if(g!==undefined&&v.generation!==g)fail('MIXED_GENERATION','$.generation');if(s!==undefined&&v.residentSchemaVersion!==s)fail('MIXED_SCHEMA','$.residentSchemaVersion');return copy(v);}
function buildMonthShard({generation:g,residentSchemaVersion:s,monthKey:m,data:d}){gen(g,'$.generation');schema(s,'$.residentSchemaVersion');month(m,'$.monthKey');object(d,'$.data');return Object.freeze({format:'zerobudget-active-month',formatVersion:1,layout:'month-sharded',generation:g,residentSchemaVersion:s,monthKey:m,data:copy(d)});}
function parseMonthShard(t,g,s,m){const v=parse(t);common(v,'zerobudget-active-month',['format','formatVersion','layout','generation','residentSchemaVersion','monthKey','data']);if(v.layout!=='month-sharded')fail('INVALID_LAYOUT','$.layout');gen(v.generation,'$.generation');schema(v.residentSchemaVersion,'$.residentSchemaVersion');month(v.monthKey,'$.monthKey');object(v.data,'$.data');if(g!==undefined&&v.generation!==g)fail('MIXED_GENERATION','$.generation');if(s!==undefined&&v.residentSchemaVersion!==s)fail('MIXED_SCHEMA','$.residentSchemaVersion');if(m!==undefined&&v.monthKey!==m)fail('MIXED_MONTH','$.monthKey');return copy(v);}
function checkStaged(keys,g){if(!Array.isArray(keys))fail('EXPECTED_ARRAY','$.stagedKeys');const seen=new Set();keys.forEach((k,i)=>{if(typeof k!=='string'||!(k===globalKey(g)||k===manifestKey(g)||k.startsWith(`${MONTH_PREFIX}${g}:`)))fail('INVALID_KEY_REFERENCE',`$.stagedKeys[${i}]`);if(k.startsWith(MONTH_PREFIX))month(k.slice(`${MONTH_PREFIX}${g}:`.length),`$.stagedKeys[${i}]`);if(seen.has(k))fail('DUPLICATE_KEY',`$.stagedKeys[${i}]`);seen.add(k);});}
function buildJournal({txId,baseMode,baseGeneration,nextGeneration,residentSchemaVersion,stagedKeys,startedAt,expiresAt}){gen(txId,'$.txId');gen(nextGeneration,'$.nextGeneration');if(txId!==nextGeneration)fail('MIXED_GENERATION','$.txId');if(!['legacy','sharded'].includes(baseMode))fail('INVALID_BASE_MODE','$.baseMode');if(baseMode==='legacy'?baseGeneration!==null:typeof baseGeneration!=='string')fail('INVALID_BASE_GENERATION','$.baseGeneration');if(baseGeneration!==null)gen(baseGeneration,'$.baseGeneration');schema(residentSchemaVersion,'$.residentSchemaVersion');checkStaged(stagedKeys,nextGeneration);stamp(startedAt,'$.startedAt');time(expiresAt,'$.expiresAt');return Object.freeze({format:'zerobudget-active-journal',formatVersion:1,txId,baseMode,baseGeneration,nextGeneration,residentSchemaVersion,manifestKey:manifestKey(nextGeneration),stagedKeys:Object.freeze([...stagedKeys]),startedAt,expiresAt});}
function parseJournal(t){const v=parse(t);common(v,'zerobudget-active-journal',['format','formatVersion','txId','baseMode','baseGeneration','nextGeneration','residentSchemaVersion','manifestKey','stagedKeys','startedAt','expiresAt']);gen(v.txId,'$.txId');gen(v.nextGeneration,'$.nextGeneration');if(v.txId!==v.nextGeneration)fail('MIXED_GENERATION','$.txId');if(!['legacy','sharded'].includes(v.baseMode))fail('INVALID_BASE_MODE','$.baseMode');if(v.baseMode==='legacy'?v.baseGeneration!==null:typeof v.baseGeneration!=='string')fail('INVALID_BASE_GENERATION','$.baseGeneration');if(v.baseGeneration!==null)gen(v.baseGeneration,'$.baseGeneration');schema(v.residentSchemaVersion,'$.residentSchemaVersion');stamp(v.startedAt,'$.startedAt');time(v.expiresAt,'$.expiresAt');if(v.manifestKey!==manifestKey(v.nextGeneration))fail('INVALID_KEY_REFERENCE','$.manifestKey');checkStaged(v.stagedKeys,v.nextGeneration);return copy(v);}
function clockNow(now,error){try{const v=now();if(!(v instanceof Date)||!Number.isFinite(v.getTime()))throw 0;return v.getTime();}catch{throw error('CLOCK_FAILED');}}
function createCoordinator({storage,now,ownerId,lockKey=WRITE_LOCK_KEY,ttlMs=DEFAULT_LOCK_TTL_MS,error=c=>err(c)}){function readLock(){let raw;try{raw=storage.getItem(lockKey);}catch{throw error('STORAGE_READ_FAILED');}if(raw===null)return null;try{const v=JSON.parse(raw);return typeof v.ownerId==='string'&&Number.isFinite(v.expiresAt)?v:null;}catch{return null;}}function acquire(){const ts=clockNow(now,error),current=readLock();if(current&&current.ownerId!==ownerId&&current.expiresAt>ts)throw error('STORE_BUSY');const lock={ownerId,expiresAt:ts+ttlMs};try{storage.setItem(lockKey,JSON.stringify(lock));}catch{throw error('STORE_BUSY');}const claimed=readLock();if(!claimed||claimed.ownerId!==ownerId||claimed.expiresAt!==lock.expiresAt)throw error('STORE_BUSY');return lock;}function release(){try{const current=readLock();if(!current||current.ownerId!==ownerId)return true;storage.removeItem(lockKey);return true;}catch{return false;}}return Object.freeze({acquire,release,readLock});}
function createShardedCoordinator({storage,now,ownerId,revision='legacy',lockKey=WRITE_LOCK_KEY,ttlMs=SHARDED_LOCK_TTL_MS,renewalMs=DEFAULT_LOCK_RENEWAL_MS,error=c=>err(c)}){if(typeof ownerId!=='string'||!ownerId)throw error('INVALID_OWNER');if(!(revision==='legacy'||GEN.test(revision)))throw error('INVALID_REVISION');function readLock(){let raw;try{raw=storage.getItem(lockKey);}catch{throw error('STORAGE_READ_FAILED');}if(raw===null)return null;try{const v=JSON.parse(raw);exact(v,['ownerId','revision','heartbeatAt','expiresAt']);if(typeof v.ownerId!=='string'||!v.ownerId||!(v.revision==='legacy'||GEN.test(v.revision))||!Number.isSafeInteger(v.heartbeatAt)||!Number.isSafeInteger(v.expiresAt)||v.expiresAt<v.heartbeatAt)return null;return v;}catch{return null;}}function write(ts){const lock={ownerId,revision,heartbeatAt:ts,expiresAt:ts+ttlMs};try{storage.setItem(lockKey,JSON.stringify(lock));}catch{throw error('STORE_BUSY');}const got=readLock();if(!got||got.ownerId!==ownerId||got.revision!==revision||got.heartbeatAt!==ts||got.expiresAt!==lock.expiresAt)throw error('STORE_BUSY');return lock;}function acquire(){const ts=clockNow(now,error),v=readLock();if(v&&v.ownerId!==ownerId&&v.expiresAt>ts)throw error('STORE_BUSY');return write(ts);}function renew(){const ts=clockNow(now,error),v=readLock();if(!v||v.ownerId!==ownerId||v.revision!==revision||v.expiresAt<=ts)throw error('STORE_BUSY');return write(ts);}function shouldRenew(lock){return clockNow(now,error)-lock.heartbeatAt>=renewalMs;}function release(){try{const v=readLock();if(!v||v.ownerId!==ownerId)return true;storage.removeItem(lockKey);return true;}catch{return false;}}return Object.freeze({acquire,renew,shouldRenew,release,readLock});}
return Object.freeze({ROOT_KEY,JOURNAL_KEY,WRITE_LOCK_KEY,MANIFEST_PREFIX,GLOBAL_PREFIX,MONTH_PREFIX,DEFAULT_LOCK_TTL_MS,SHARDED_LOCK_TTL_MS,DEFAULT_LOCK_RENEWAL_MS,FORMAT_VERSION,createGenerationId,manifestKey,globalKey,monthKey,utf8Length,sha256,globalReference,monthReference,validateGlobalReference,validateMonthReference,buildRootPointer,parseRootPointer,buildManifest,parseManifest,buildGlobalShard,parseGlobalShard,buildMonthShard,parseMonthShard,buildJournal,parseJournal,createCoordinator,createShardedCoordinator});
});
